host = "0.0.0.0"
port = 8080
encryption_key = "default_key_change_me"
client_timeout = 300
max_clients = 1000
log_file = "c2_server.log"
enable_audit = true

[web]
enabled = true
static_dir = "web/static"
template_dir = "templates"
enable_cors = true

[auth]
username = "Rust-Admin"
password = "Passwd@RustC2"